from fpdf import FPDF
from datetime import datetime
import io

class LegalPDFGenerator:
    def __init__(self):
        self.pdf = FPDF()
        self.pdf.set_auto_page_break(auto=True, margin=15)
        
    def generate_report(self, report, party_a_name="Party A", party_b_name="Party B"):
        self.pdf.add_page()
        
        # Header
        self.pdf.set_font("helvetica", "B", 20)
        self.pdf.set_text_color(49, 130, 206) # Blue color
        self.pdf.cell(0, 15, "Legal Conflict & Mediation Report", ln=True, align="C")
        
        self.pdf.set_font("helvetica", "", 10)
        self.pdf.set_text_color(100, 100, 100)
        self.pdf.cell(0, 5, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align="C")
        self.pdf.cell(0, 10, "Generated by Legal AI Portal (MVA 1988 Compliance)", ln=True, align="C")
        self.pdf.ln(10)
        
        # --- Section 1: Case Summary ---
        self.pdf.set_text_color(0, 0, 0)
        self.pdf.set_font("helvetica", "B", 14)
        self.pdf.set_fill_color(240, 240, 240)
        self.pdf.cell(0, 10, " 1. Case Summary", ln=True, fill=True)
        self.pdf.ln(2)
        
        self.pdf.set_font("helvetica", "B", 11)
        self.pdf.cell(40, 8, f"{party_a_name}:", ln=False)
        self.pdf.set_font("helvetica", "", 11)
        self.pdf.multi_cell(0, 8, "Statement analyzed and cross-referenced with database.")
        
        self.pdf.set_font("helvetica", "B", 11)
        self.pdf.cell(40, 8, f"{party_b_name}:", ln=False)
        self.pdf.set_font("helvetica", "", 11)
        self.pdf.multi_cell(0, 8, "Statement analyzed for legal risk exposure.")
        self.pdf.ln(5)
        
        # --- Section 2: Legal Verdict ---
        self.pdf.set_font("helvetica", "B", 14)
        self.pdf.set_fill_color(230, 242, 255)
        self.pdf.cell(0, 10, " 2. Legal Verdict & Violations", ln=True, fill=True)
        self.pdf.ln(2)
        
        self.pdf.set_font("helvetica", "B", 11)
        self.pdf.cell(50, 8, "Violation Detected:", ln=False)
        self.pdf.set_font("helvetica", "", 11)
        self.pdf.multi_cell(0, 8, report.legal_analysis.detected_violation)
        
        self.pdf.set_font("helvetica", "B", 11)
        self.pdf.cell(50, 8, "Applicable Section:", ln=False)
        self.pdf.set_font("helvetica", "", 11)
        self.pdf.multi_cell(0, 8, f"Section {report.legal_analysis.relevant_section} of MVA 1988")
        
        self.pdf.set_font("helvetica", "B", 11)
        self.pdf.cell(50, 8, "Proposed Penalty:", ln=False)
        self.pdf.set_font("helvetica", "B", 11)
        self.pdf.set_text_color(200, 0, 0)
        self.pdf.multi_cell(0, 8, report.legal_analysis.possible_penalty)
        self.pdf.set_text_color(0, 0, 0)
        self.pdf.ln(5)
        
        # --- Section 3: Risk Assessment ---
        self.pdf.set_font("helvetica", "B", 14)
        self.pdf.cell(0, 10, " 3. Legal Risk Exposure", ln=True)
        self.pdf.ln(2)
        
        self.pdf.set_font("helvetica", "B", 11)
        self.pdf.cell(0, 8, f"Risk for {party_a_name}:", ln=True)
        self.pdf.set_font("helvetica", "", 10)
        self.pdf.multi_cell(0, 6, str(report.legal_risk_assessment.party_a_legal_risk or 'Minimal'))
        self.pdf.ln(3)
        
        self.pdf.set_font("helvetica", "B", 11)
        self.pdf.cell(0, 8, f"Risk for {party_b_name}:", ln=True)
        self.pdf.set_font("helvetica", "", 10)
        self.pdf.multi_cell(0, 6, str(report.legal_risk_assessment.party_b_legal_risk or 'Minimal'))
        self.pdf.ln(5)
        
        # --- Section 4: Resolution & Mediation ---
        self.pdf.set_font("helvetica", "B", 14)
        self.pdf.set_fill_color(235, 255, 235)
        self.pdf.set_text_color(0, 100, 0)
        self.pdf.cell(0, 10, " 4. Recommended Resolution", ln=True, fill=True)
        self.pdf.ln(2)
        
        self.pdf.set_font("helvetica", "B", 11)
        self.pdf.multi_cell(0, 8, "Primary Action Plan:")
        self.pdf.set_font("helvetica", "", 11)
        self.pdf.set_text_color(0, 0, 0)
        self.pdf.multi_cell(0, 7, report.resolution_suggestion.suggested_legal_action)
        self.pdf.ln(3)
        
        self.pdf.set_font("helvetica", "I", 10)
        self.pdf.multi_cell(0, 6, f"Mediation Advice: {report.resolution_suggestion.suggested_mediation_advice}")
        self.pdf.ln(10)
        
        # Footer Note
        self.pdf.set_font("helvetica", "I", 8)
        self.pdf.set_text_color(150, 150, 150)
        self.pdf.multi_cell(0, 5, "Disclaimer: This report is generated by an AI assistant based on the Motor Vehicles Act 1988 and provided evidence. It does not constitute formal legal advice. Please consult a qualified legal professional for official proceedings.", align="C")
        
        # Return as bytes
        return self.pdf.output()
